### ISSUE TITLE
Subscription: custom_data is None or account_id not in custom_data

### ISSUE THREAD

**Issue by DeeeeLAN** [websideproject/django-paddle-billing#70]
## 🐛 Bug Report

I hit the following error when a subscription tried to post from paddle to the webhook:

```
DjangoPaddleBillingError at /paddle/webhook/
Subscription: custom_data is None or account_id not in custom_data
```

I am not sure what account_id is supposed to be - it is nowhere to be found in the subscription webhook payload. Since we already receive customer_id from the payload, I assume that would be sufficient to link the subscription to a particular user.

**Comment by bgervan** [comment]
You set custom_data when you create the subscription on the frontend side. You send the requests to paddle, and there is a need to identify a specific subscription with a user when you receive the webhook. You can use account_id as identifier (if user is your account model, this will be the user_id) 

When you create the subscription with a specific email, the custom data is not sent along with the customer creation (a few months ago this was the case for sure), but only with the subscription, so in order to make sure the connection, we need account_id in the custom data and connect it to the Subscription.

Subscription is connected to AccountModel (can be the User model, but can be Workspace as well), Customer is connected to User (soft relation, can be null, as the email address can be unknown, for example if the user signed up via facebook/github, you are not necessary know the email address)

**Comment by acalderon85** [comment]
@DeeeeLAN this is not a bug.

Suppose you have an app in Django called KeepTrack for managing personal goals.

When someone creates an account in KeepTrack and then buys a subscription through Paddle, you need to link that subscription to that KeepTrack account. That's what the account_id is for.

The customer_id you're talking about is the customer_id in Paddle's database, not your Django database.

@alifanov check out Paddle's documentation here: https://developer.paddle.com/build/checkout/build-overlay-checkout

One way to pass items and settings is through the Checkout.open() function, for example:

```// open checkout
function openCheckout(items, customer) {
  Paddle.Checkout.open({
    items: items,
    customer: customer,
    customData: {
      "account_id": 1
    }
  });
}
```

But you can also use html data attributes or the Initialize() method, as per documentation.

**Comment by bgervan** [comment]
@acalderon85 thanks for the detailed answer. Indeed it is not a bug itself, but a recent PR allows the account_id to be optional. Although it can generate issues on the data, if it's not skipped on purpose. 

@alifanov did the above explanation help you get started? Feel free to open a discussion in case you have additional questions.
